### ISSUE TITLE
OutOfMemory Error when building the project with Docker

### ISSUE THREAD

**Issue by dfernandezm** [micronaut-guides/micronaut-creating-first-graal-app#20]
```
./gradlew assemble
./docker-build.sh
```

```
[micronaut-graal-app:27]    classlist:   9,286.57 ms,  1.11 GB
[micronaut-graal-app:27]        (cap):     911.42 ms,  1.13 GB
[micronaut-graal-app:27]        setup:   2,621.70 ms,  1.13 GB
[micronaut-graal-app:27]     (clinit):     864.16 ms,  1.49 GB
[micronaut-graal-app:27]   (typeflow):  16,112.87 ms,  1.49 GB
[micronaut-graal-app:27]    (objects):  18,721.41 ms,  1.49 GB
[micronaut-graal-app:27]   (features):   2,877.68 ms,  1.49 GB
[micronaut-graal-app:27]     analysis:  40,802.49 ms,  1.49 GB
[micronaut-graal-app:27]     universe:   1,849.98 ms,  1.46 GB
[micronaut-graal-app:27]      (parse):  21,785.17 ms,  1.36 GB
Exception in thread "native-image pid watcher" java.lang.OutOfMemoryError: Java heap space
[micronaut-graal-app:27]     (inline): 1,326,066.84 ms,  1.36 GB
[micronaut-graal-app:27]      compile: 1,607,428.12 ms,  1.36 GB
Exception in thread "Libgraal MBean Registration" java.lang.OutOfMemoryError: Java heap space
4 fatal errors detected:
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.OutOfMemoryError: Java heap space
	at method: void org.graalvm.collections.EconomicMapImpl.createHash()
	at com.oracle.svm.hosted.code.CompileQueue.doInlineTrivial(CompileQueue.java:599)
	at com.oracle.svm.hosted.code.CompileQueue.access$000(CompileQueue.java:156)
	at com.oracle.svm.hosted.code.CompileQueue$TrivialInlineTask.run(CompileQueue.java:284)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at sun.misc.Unsafe.allocateInstance(Native Method)
	at org.graalvm.compiler.graph.Node.clone(Node.java:1119)
	at org.graalvm.compiler.graph.NodeClass.createNodeDuplicates(NodeClass.java:921)
	at org.graalvm.compiler.graph.NodeClass.addGraphDuplicate(NodeClass.java:870)
	at org.graalvm.compiler.graph.Graph.addDuplicates(Graph.java:1240)
	at org.graalvm.compiler.phases.common.inlining.InliningUtil.inline(InliningUtil.java:430)
	at org.graalvm.compiler.phases.common.inlining.InliningUtil.inline(InliningUtil.java:344)
	at com.oracle.svm.hosted.code.CompileQueue.tryInlineTrivial(CompileQueue.java:616)
	at com.oracle.svm.hosted.code.CompileQueue.doInlineTrivial(CompileQueue.java:581)
	at com.oracle.svm.hosted.code.CompileQueue.access$000(CompileQueue.java:156)
	at com.oracle.svm.hosted.code.CompileQueue$TrivialInlineTask.run(CompileQueue.java:284)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at com.oracle.graal.pointsto.util.CompletionExecutor$$Lambda$241/1598657329.run(Unknown Source)
	... 5 more
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.OutOfMemoryError: Java heap space
	at method: void javax.security.auth.login.LoginContext.invoke(String)
	at com.oracle.svm.hosted.code.CompileQueue.doInlineTrivial(CompileQueue.java:599)
	at com.oracle.svm.hosted.code.CompileQueue.access$000(CompileQueue.java:156)
	at com.oracle.svm.hosted.code.CompileQueue$TrivialInlineTask.run(CompileQueue.java:284)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
Caused by: java.lang.OutOfMemoryError: Java heap space
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.OutOfMemoryError: Java heap space
	at method: int org.graalvm.collections.EconomicMapImpl.findAndRemoveWithCollision(Object, EconomicMapImpl$CollisionLink, int)
```

**Comment by ilopmar** [comment]
You need to make sure you have enough memory and configure Docker to use it.

**Comment by dfernandezm** [comment]
Thanks! I got it to build giving 6GB to docker on Mac... but how would this work in a CI environment where memory could be more contentious?

**Comment by ilopmar** [comment]
I always recommend giving it at least 8GB of RAM. Depending on the application it may need even more RAM.

For CI environments, you have two options:
- It may take more time because during the generating of the native image there is no much memory and the process starts swapping. At the end you get the native image but instead of taking 3 minutes to build it, it takes 20.
- It fails with an OOM (like happened to you), the only option is to increase the RAM.

This happens to us when doing the integration tests between Micronaut and GraalVM and for some applications we have specific runners with more RAM because with the Gitlab CI shared runners we simply can't build those apps.

I'm closing this issue but feel free to comment here if you need anything else :)
